---
title: 'univariate analysis: UB55'
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    highlight: zenburn
---


# intro


```{r setup, include = FALSE}

source(here::here("code", "_packages.R"))
source(here("code", "read-behav.R"))
source(here("code", "_vars.R"))
source(here("code", "_atlases.R"))
source(here("code", "_settings.R"))

## data ----

glminfo <- data.frame(
  task = c("Axcpt", "Cuedts", "Stern", "Stroop"),
  name.glm = c(
    "baseline_Cues_EVENTS_censored_shifted", 
    "baseline_CongruencySwitch_EVENTS_censored_shifted",
    "baseline_ListLength_EVENTS_censored_shifted",
    "baseline_Congruency_EVENTS_censored_shifted"
  )
)
glminfo <- as.data.table(glminfo)

d <- setNames(vector("list", nrow(glminfo)), glminfo$task)
for (glm.i in seq_len(nrow(glminfo))) {
  
  a <- readRDS(here("out", "glms", paste0("roistats_", glminfo[glm.i]$task, "_", glminfo[glm.i]$name.glm, ".RDS")))
  a <- a[, , subjs[!subjs %in% "432332"], , ]
  a <- as.data.table(reshape2::melt(a))
  
  a <- separate(a, term, c("term", "stat"), "_")
  a <- a[!grepl("Full|block", term) & stat != "Fstat"]
  a <- separate(a, term, c("term", "tr"), "#")
  
  a$network <- a$parcel %>% gsub("^Mean_7Networks_LH_", "", .) %>% gsub("_.*", "", .)
  
  a <- dcast(a, term + tr + parcel + subj + run + hemi + network ~ stat, value.var = "value")
  names(a) <- tolower(names(a))
  
  a$parcel <- ifelse(
    a$hemi == "L",
    as.character(a$parcel),
    gsub("7Networks_LH", "7Networks_RH", as.character(a$parcel))
  )

  d[[glm.i]] <- a
  
}
rm(glm.i, a)


```


# Group

## AXCPT

### curves

#### Network-level

##### marginal

```{r group_axcpt_curves_network_marginal, fig.height = 7, fig.width = 14}

d$Axcpt[, .(m = mean(coef)), by = .(run, network, tr, subj)] %>%
  
  mutate(tr = as.numeric(tr)) %>%
  
  ggplot(aes(tr, m, fill = run)) +
  geom_hline(yintercept = 0) +
  stat_summary(fun.data = "mean_cl_boot", geom = "ribbon", alpha = 1/3) +
  
  facet_grid(vars(network)) +
  scale_fill_brewer(type = "qual", palette = 2) +
  scale_x_continuous(breaks = seq(0, 16, 1)) +
  
  labs(y = "Mean beta", x = "TR post stimtime", title = "AXCPT marginal curves")

```

##### conditional

```{r group_axcpt_curves_network_conditional, fig.height = 7, fig.width = 11}

d$Axcpt[, .(m = mean(coef)), by = .(run, network, tr, term, subj)] %>%
  
  mutate(tr = as.numeric(tr)) %>%
  
  ggplot(aes(tr, m, fill = run)) +
  geom_hline(yintercept = 0) +
  stat_summary(fun.data = "mean_cl_boot", geom = "ribbon", alpha = 1/3) +
  
  facet_grid(vars(network), vars(term)) +
  scale_fill_brewer(type = "qual", palette = 2) +
  scale_x_continuous(breaks = seq(0, 16, 1)) +
  theme(legend.position = "none") +
  
  labs(y = "Mean beta", x = "TR post stimtime", title = "AXCPT conditional curves")

```


##### contrasts

```{r group_axcpt_curves_network_contrast, fig.height = 7, fig.width = 11}


d$Axcpt[term %in% c("BX", "BY"), .(m = mean(coef)), by = .(run, network, tr, term, subj)] %>%
  
  dcast(run + network + tr + subj ~ term, value_var = "m") %>%
  
  mutate(hilo = BX - BY, tr = as.numeric(tr)) %>%
  
  ggplot(aes(tr, hilo, fill = run)) +
  geom_hline(yintercept = 0) +
  stat_summary(fun.data = "mean_cl_boot", geom = "ribbon", alpha = 1/3) +
  
  facet_grid(vars(network)) +
  scale_fill_brewer(type = "qual", palette = 2) +
  scale_x_continuous(breaks = seq(0, 16, 1)) +
  theme(legend.position = "none") +
  
  labs(y = "Mean beta", x = "TR post stimtime", title = "AXCPT hilo curves (BX-BY)")


d$Axcpt[, .(m = mean(coef)), by = .(run, network, tr, term, subj)] %>%
  
  dcast(run + network + tr + subj ~ term, value.var = "m") %>%
  
  mutate(nogogo = (Ang + Bng)/2 - (AX + AY + BX + BY)/4, tr = as.numeric(tr)) %>%
  
  ggplot(aes(tr, nogogo, fill = run)) +
  geom_hline(yintercept = 0) +
  stat_summary(fun.data = "mean_cl_boot", geom = "ribbon", alpha = 1/3) +
  
  facet_grid(vars(network)) +
  scale_fill_brewer(type = "qual", palette = 2) +
  scale_x_continuous(breaks = seq(0, 16, 1)) +
  theme(legend.position = "none") +
  
  labs(y = "Mean beta", x = "TR post stimtime", title = "AXCPT nogo-go curves [(Ang + Bng)/2 - (AX + AY + BX + BY)/4]")


```


#### DMCC 34 HiLo

```{r group_axcpt_curves_dmcc34, fig.height = 7, fig.width = 11}

d$Axcpt$parcel <- gsub("Mean_7Networks_", "", d$Axcpt$parcel)

d$Axcpt[
  term %in% c("BX", "BY") & parcel %in% parcellation$key[dmcc34], 
  .(m = mean(coef)), by = .(run, parcel, network, tr, term, subj)
  ] %>%
  
  dcast(run + parcel + network + tr + subj ~ term, value_var = "m") %>%
  
  mutate(hilo = BX - BY, tr = as.numeric(tr)) %>%
  
  ggplot(aes(tr, hilo, fill = run)) +
  geom_hline(yintercept = 0) +
  stat_summary(fun.data = "mean_cl_boot", geom = "ribbon", alpha = 1/3) +
  
  facet_wrap(vars(parcel)) +
  scale_fill_brewer(type = "qual", palette = 2) +
  scale_x_continuous(breaks = seq(0, 16, 1)) +
  theme(legend.position = "none") +
  
  labs(y = "Mean beta", x = "TR post stimtime", title = "AXCPT hilo curves DMCC34 (BX-BY)")

```


### stats


```{r}

axcpt.hilo <- d$Axcpt[tr %in% target.trs$axcpt & term %in% c("BX", "BY")]
axcpt.hilo$term <- relevel(as.factor(axcpt.hilo$term), "BY")
axcpt.hilo <- split(axcpt.hilo, axcpt.hilo$parcel)

m.axcpt.hilo <- lapply(axcpt.hilo, function(x) lmer(coef ~ term + (1 | subj), x))
s.axcpt.hilo <- bind_rows(lapply(m.axcpt.hilo, tidy_lmer), .id = "parcel")
s.axcpt.hilo %<>% filter(term == "termBX") %>% mutate(p.holm = p.adjust(p.value, "holm"))

s.axcpt.hilo %<>%
  mutate(
    hemi = substr(parcel, 1, 1),
    num.roi = match(parcel, parcellation$key)
  )
match(s.axcpt.hilo$parcel, parcellation$key)

parcellation$key[is.na(match(s.axcpt.hilo$parcel, parcellation$key))]
setdiff(s.axcpt.hilo$parcel, parcellation$key)

setdiff(parcellation$key, s.axcpt.hilo$parcel)


s.axcpt.hilo$parcel == "LH_Cont_PFCl_9"
parcellation$key == "LH_Cont_PFCl_9"

parcellation$key <- gsub("Ins_", "_", parcellation$key)


s.axcpt.hilo$parcel[111]
s.axcpt.hilo %>% filter(p.holm < 0.05 & estimate > 0) %>% arrange(p.holm) %>% kable


setdiff(
  gsub("Mean_7Networks_", "", dimnames(a)$parcel),
  parcellation$key
)


setdiff(
  parcellation$key,
  gsub("Mean_7Networks_", "", dimnames(a)$parcel)
)

intersect(
  parcellation$key,
  gsub("Mean_7Networks_", "", dimnames(a)$parcel)
)



unique(gsub("Mean_7Networks_.H_", "", dimnames(a)$parcel))
unique(gsub(".H_", "", parcellation$key))

```


### maps


```{r}

s.axcpt.hilo %>%
  build_overlay("statistic", template = schaefer) %>%
  plot_surface(underlay = hcp)

```







