---
title: 'intersubject discrimination: univariate versus multivariate measures'
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    highlight: zenburn
    number_sections: true
    theme: spacelab
---


# intro

Purpose: 




```{r setup, include = FALSE}

source(here::here("code", "_packages.R"))
source(here("code", "read-behav.R"))
source(here("code", "_vars.R"))
source(here("code", "_atlases.R"))
source(here("code", "_settings.R"))
source(here("code", "_funs.R"))

## data ----

d <- fread(here("out", "fprint", "unimulti_hilo_target_schaefer400-07", "idi_group.csv"))

d <- d %>%
  
  group_by(transform, variable, task) %>%
  mutate(
    p.fdr = p.adjust(p, "fdr"),
    network = get.network(parcel),
    hemi = substr(parcel, 1, 1),
    num.roi = match(parcel, parcellation$key)
  ) %>%
  
  arrange(transform, variable, task, num.roi) %>%
  
  as.data.table


```

# stats

```{r, fig.width = 12, fig.height = 8}

d %>%
  
  select(task, transform, parcel, variable, estimate, p.fdr) %>%
  dcast(task + transform + parcel ~ variable, value.var = c("estimate", "p.fdr")) %>%
  
  ggplot(aes(estimate_multivariate, estimate_univariate)) +
  
  geom_abline() +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point() +
  geom_point(size = 2, color = "white", shape = 21, aes(fill = p.fdr_multivariate < 0.05 | p.fdr_univariate < 0.05)) +
  
  scale_fill_manual(
    values = c("TRUE" = "firebrick", "FALSE" = "black"), 
    labels = c("TRUE" = "pFDR<0.05", "FALSE" = "pFDR>=0.05"),
    name = NULL
    ) +
  theme(legend.position = "top") +
  
  facet_grid(vars(transform), cols = vars(task), scales = "free") +
  
  labs(
    title = "mean univariate versus multivariate contrasts per parcel: scaled", 
    x = "multivariate contrast (b/n - w/i)", 
    y = "univariate contrast (b/n - w/i)",
    caption = "p-value from non-parametric bootstrap"
    )


```

```{r fig.width = 8, fig.height = 11}

d %>%
  
  filter(transform == "unscaled") %>%
  
  
  dcast(task + transform + parcel ~ variable, value.var = c("estimate", "p.fdr")) %>%
  filter(estimate_multivariate > 0, estimate_univariate > 0) %>%
  
  
  ggplot(aes(estimate_multivariate, estimate_univariate, color = p.fdr_contrast < 0.05)) +
  
  geom_abline() +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point() +
  
  facet_grid(cols = vars(task), rows = vars(get.network(parcel)), scales = "free") +
  
  scale_color_manual(
    values = c("TRUE" = "firebrick", "FALSE" = "black"), 
    labels = c("TRUE" = "pFDR<0.05", "FALSE" = "pFDR>=0.05"),
    name = NULL
    ) +
  theme(legend.position = "top") +
  
  scale_x_continuous(n.breaks = 3) +
  scale_y_continuous(n.breaks = 3) +
  
  labs(
    title = "mean univariate versus multivariate contrasts per parcel: unscaled", 
    x = "multivariate contrast (b/n - w/i)", 
    y = "univariate contrast (b/n - w/i)",
    caption = "p-value from non-parametric bootstrap\nplots exclude contrasts<0"
    )




d %>%
  
  filter(transform == "scaled") %>%
  
  
  dcast(task + transform + parcel ~ variable, value.var = c("estimate", "p.fdr")) %>%
  filter(estimate_multivariate > 0, estimate_univariate > 0) %>%
  
  
  ggplot(aes(estimate_multivariate, estimate_univariate, color = p.fdr_contrast < 0.05)) +
  
  geom_abline() +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  geom_point() +
  
  facet_grid(cols = vars(task), rows = vars(get.network(parcel)), scales = "free") +
  
  scale_color_manual(
    values = c("TRUE" = "firebrick", "FALSE" = "black"), 
    labels = c("TRUE" = "pFDR<0.05", "FALSE" = "pFDR>=0.05"),
    name = NULL
    ) +
  theme(legend.position = "top") +
  
  scale_x_continuous(n.breaks = 3) +
  scale_y_continuous(n.breaks = 3) +
  
  labs(
    title = "mean univariate versus multivariate contrasts per parcel: scaled", 
    x = "multivariate contrast (b/n - w/i)", 
    y = "univariate contrast (b/n - w/i)",
    caption = "p-value from non-parametric bootstrap\nplots exclude contrasts<0"
    )


```



# maps

```{r brains, fig.width = 15, results = "asis"}


for (task.i in tasks) {
  
  cat(sprintf("\n## %s", task.i))
  cat("\n")
  
  for (variable.i in c("univariate", "multivariate", "contrast")) {

    cat(sprintf("\n### %s", variable.i))
    cat("\n")
    
    for (transform.i in c("unscaled", "scaled")) {
      
      cat(sprintf("\n#### %s ", transform.i))
      # cat("\n")
      
      d %>%
        
        filter(task == task.i, transform == transform.i, variable == variable.i) %>%
    
        build_overlay("estimate", template = schaefer) %>%
        plot_surface(underlay = hcp, hues = viridis::inferno(500))
      
      d %>%
        
        filter(task == task.i, transform == transform.i, variable == variable.i) %>%
        mutate(estimate = ifelse(p.fdr > 0.05, estimate, 0)) %>%

        build_overlay("estimate", template = schaefer) %>%
        plot_surface(underlay = hcp, hues = viridis::inferno(500))
      
    }
    
  }
    
}


```

