---
title: 'multitask RSA: prelim cross-run analysis'
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    highlight: zenburn
    number_sections: true
    theme: spacelab
---


# intro

## Purpose


```{r setup, include = FALSE}

source(here::here("code", "_packages.R"))
source(here("code", "read-behav.R"))
source(here("code", "_vars.R"))
suppressWarnings(source(here("code", "_atlases.R")))
source(here("code", "_settings.R"))
source(here("code", "_funs.R"))

library(ggridges)


subjs <- subjs[!subjs %in% "432332"]



dirs <- expand.grid(subj = subjs, task = tasks, session = "baseline", stringsAsFactors = FALSE)
glminfo <- data.frame(
  task = c("Axcpt", "Cuedts", "Stern", "Stroop"),#, "Stroop"),
  name.glm = c(
    "baseline_Cues_EVENTS_censored_shifted", 
    "baseline_CongruencySwitch_EVENTS_censored_shifted",
    "baseline_ListLength_EVENTS_censored_shifted",
    "baseline_Congruency_EVENTS_censored_shifted"
    # "baseline_fix-item_EVENTS_censored"
  )
)
glminfo <- as.data.table(glminfo)

networks <- unique(get.network(parcellation$key))


```





```{r fig.width = 16}



for (glm.i in seq_len(nrow(glminfo))) {
  # glm.i = 4
  
  name.glm.i <- glminfo[glm.i]$name.glm
  name.task.i <- glminfo[glm.i]$task
  
  
  X <- readRDS(here("out", "glms", paste0("xmats_", name.task.i, "_", name.glm.i, ".RDS")))
  
  S <- readRDS(
    here(
      "out", "taskcoding", paste0("correlation-crossrun_", glminfo[glm.i]$task, "_", glminfo[glm.i]$name.glm,  ".RDS")
      )
  )
  
  rmcols <- grep("Pol|block#0|is.included|movregs", dimnames(X)$regressor)
  plot(rowSums(X[, -rmcols, 1, 1]))
  
  
  nrow(X[rowSums(X[, -rmcols, 1, 1]) < 3 & rowSums(X[, -rmcols, 1, 1]) > 1, -rmcols, 1, 1])
  nrow(X[rowSums(X[, -rmcols, 1, 1]) > 2 & rowSums(X[, -rmcols, 1, 1]) > 1, -rmcols, 1, 1])
  
  is.rest.tr <- !(apply(X[, "block#0", , ], "tr", mean, na.rm = TRUE) > 0)
  
  S_bar <- apply(atanh(S), 1:3, mean, na.rm = TRUE)
  
  S_rest <- as.matrix(is.rest.tr) %*% t(as.matrix(is.rest.tr))
  matplot(S_rest)
  
  x_rest <- S_rest[lower.tri(S_rest)]
  x_rest <- x_rest / sum(x_rest)
  
  x_task <- !S_rest[lower.tri(!S_rest)]
  x_task <- x_task / sum(x_task)
  x_rest %*% x_task
  
  plot(
    apply(S_bar, "network", function(x) x[lower.tri(x)] %*% x_task),
    apply(S_bar, "network", function(x) x[lower.tri(x)] %*% x_rest)
  )
  
  apply(S_bar, "network", function(x) x[lower.tri(x)] %*% x_task)
  apply(S_bar, "network", function(x) x[lower.tri(x)] %*% x_rest)

  abline(0, 1)
  
  
  S_bar.sort <- S_bar[c(which(is.rest.tr), which(!is.rest.tr)), , ]
  
  matplot(S_bar[, , "Limbic"])
  matplot(S_bar[, , "Cont"])
  matplot(S_bar[, , "Default"])
  matplot(S_bar[, , "DorsAttn"])
  matplot(S_bar[, , "SalVentAttn"])
  matplot(S_bar[, , "Vis"])
  matplot(S_bar[, , "SomMot"])
  
  

}



```


