---
title: "Design matrix QC, UB55, trial-wise"
author: "mike freund"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    highlight: zenburn
---


```{r setup, include = FALSE}

## TODO:
## vif as function of dropping terms
##   - cumulative: polort 5, 5+4, 5+4+3, ..., 
##   - each own
## correlation matrices
## problem subjects:
##   - with > 10 vif for regressors of interest: why?
##      - co-linearity with motion, polort, as result of censoring?
##      
##  1. ID 'bad subjects' for each regressor of interest with threshold on VIF
##  2. plot motion R^2, polort R^2, param of interest R^2, by group (bad, good subj)
##  3. 
##    correlation wtih censoring by group
##    # frames censored by group
##    ssq(fd) by group

knitr::opts_chunk$set(echo = FALSE, fig.align = 'center', cache = TRUE)

library(here)
library(dplyr)
library(magrittr)
library(data.table)
library(mikeutils)
library(gifti)
library(cifti)
library(abind)

library(ggplot2)
library(grid)
library(gridExtra)
library(cowplot)

source(here("code", "glms", "write-events_funs.R"))
source(here("code", "read-behav.R"))
source(here("code", "_vars.R"))

## settings

theme_set(theme_bw(base_size = 12))

## xmats
xmat_stroop <- readRDS(here("out", "glms", "xmats_Stroop_baseline_fix-LSA_EVENTS_censored.RDS"))[, , !subjs %in% "432332", ]

```

# About


# VIF



```{r vifs, warning = FALSE}

vifs <- function(X) {
  
  
  vifs.i <- apply(
    X, 
    c("subj", "run"), 
    function(d) {
      # d <- xmat_stroop[, , 1, 1]
      
      d <- as.data.frame(d)
      
      ## censor:
      is.included <- as.logical(d$is.included)
      d$is.included <- NULL
      d <- d[is.included, ]
      
      car::vif(lm(1:nrow(d) ~ . - 1, d))

      }
    )
  
  vifs.i <- reshape2::melt(vifs.i, value.name = "vif", varnames = c("regressor", "subj", "run"))


  vifs.i$regressor.type <- ""
  vifs.i$regressor.type[grep("block", vifs.i$regressor)] <- "block"
  vifs.i$regressor.type[grep("movreg", vifs.i$regressor)] <- "movreg"
  vifs.i$regressor.type[grep("Pol", vifs.i$regressor)] <- "polort"
  vifs.i$regressor.type[-grep("block|movreg|Pol", vifs.i$regressor)] <- "event"

  vifs.i
 
}


vifs_stroop <- vifs(xmat_stroop)


```


# distribution of VIFs for "regressors of interest" across subjects


```{r vifs_plot, fig.width = 10, fig.height = 15}

vifs_stroop %>%
  
  filter(regressor.type %in% "event") %>%
  
  ggplot(aes(vif, regressor)) +
  geom_boxplot() +
  facet_grid(cols = vars(run))

```


```{r}

R <- array(
  NA, 
  dim = c(
    length(dimnames(xmat_stroop)$regressor) - 2,
    length(dimnames(xmat_stroop)$regressor) - 2,
    length(dimnames(xmat_stroop)$subj)
  ),
  dimnames = list(
    .row = setdiff(dimnames(xmat_stroop)$regressor, c("is.included", "Run#1Pol#0")),
    .col = setdiff(dimnames(xmat_stroop)$regressor, c("is.included", "Run#1Pol#0")),
    subj = dimnames(xmat_stroop)$subj
  )
  )

for (subj.i in dimnames(xmat_stroop)$subj) {
  
  for (run.i in 1:2) {
    
    d <- xmat_stroop[, , 1, 1]
    d <- as.data.frame(d)
    
    ## censor:
    is.included <- as.logical(d$is.included)
    d[c("is.included", "Run#1Pol#0")] <- NULL
    d <- d[is.included, ]
    
    R[, , subj.i] <- cor(d)  
    
    
  }
  
}

Rbar <- tanh(apply(atanh(R), 1:2, mean))
qcor(Rbar)


qcor(Rbar[grep("block|movregs", colnames(Rbar)), ])

qcor(Rbar[grep("PC50", colnames(Rbar)), ])

Rbar_events <- Rbar[-grep("block|movregs", colnames(Rbar)), -grep("block|movregs", colnames(Rbar))]
max(abs(Rbar_events[lower.tri(Rbar_events)]))
qcor(Rbar_events)
plot(Rbar_events[lower.tri(Rbar_events)])


```

