---
title: 'UB55 multivariate analysis: hi-lo contrast, individual-level'
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    highlight: zenburn
    number_sections: true
    theme: spacelab

---


# intro

Purpose: 

Explore individual differences in multivariate fMRI contrasts (cross-validated euclidean).

1. anatomical dissociations: cross-region correlations
2. task-generality: cross-task correlations



```{r setup, include = FALSE}


source(here::here("code", "_packages.R"))
source(here("code", "read-behav.R"))
source(here("code", "_vars.R"))
source(here("code", "_atlases.R"))
source(here("code", "_settings.R"))
source(here("code", "_funs.R"))

## data ----

similtype <- c(
  "euclidean-cv-unsta-unpre"
  # "euclidean-cv-unsta-prewh", "euclidean-cv-stand-prewh", "euclidean-cv-unsta-unpre", "euclidean-cv-stand-unpre"
  )

glminfo <- data.frame(
  task = c("Axcpt", "Cuedts", "Stern", "Stroop"),
  name.glm = c(
    "baseline_Cues_EVENTS_censored_shifted", 
    "baseline_CongruencySwitch_EVENTS_censored_shifted",
    "baseline_ListLength_EVENTS_censored_shifted",
    "baseline_Congruency_EVENTS_censored_shifted"
  )
)
glminfo <- as.data.table(glminfo)

weights_hi <- list(
  Axcpt  = c(AX = 0, AY = 0, Ang = 0, BX = 1, BY = 0, Bng = 0),
  Cuedts = c(ConInc = 0, ConNoInc = 0, InConInc = 1, InConNoInc = 1) / 2,
  Stern  = c(LL5NP = 0, LL5NN = 0, LL5RN = 1, not5NP = 0, not5NN = 0, not5RN = 0),
  Stroop = c(PC50Con = 0, PC50InCon = 1, biasCon = 0, PC50InCon = 1) / 2
)

weights_lo <- list(
  Axcpt  = c(AX = 0, AY = 0, Ang = 0, BX = 0, BY = 1, Bng = 0),
  Cuedts = c(ConInc = 1, ConNoInc = 1, InConInc = 0, InConNoInc = 0) / 2,
  Stern  = c(LL5NP = 0, LL5NN = 1, LL5RN = 0, not5NP = 0, not5NN = 0, not5RN = 0),
  Stroop = c(PC50Con = 1, PC50InCon = 0, biasCon = 1, PC50InCon = 0) / 2
)


d <- setNames(vector("list", nrow(glminfo)), glminfo$task)
for (rsa.i in similtype) {
  # rsa.i = similtype[1]
  
  l <- setNames(vector("list", nrow(glminfo)), glminfo$task)
  for (glm.i in seq_len(nrow(glminfo))) {
    # glm.i = 2
    
    a <- readRDS(here("out", "rsa", paste0(rsa.i, "_", glminfo[glm.i]$task, "_", glminfo[glm.i]$name.glm, ".RDS")))
    a <- apply(a[, , target.trs[[glm.i]], , ], c(".row", ".col", "parcel", "subj"), mean)  ## average across target TRs
    
    sds <- apply(a, c("parcel", "subj"), function(x) sd(x[lower.tri(x)]))  ## scale by standard devs w/in RDM
    a <- sweep(a, MARGIN = 3:4, STATS = sds, FUN = "/")
    a <- apply(a, c("parcel", "subj"), function(x) weights_lo[[glm.i]] %*% x %*% weights_hi[[glm.i]])
    a <- as.data.table(reshape2::melt(a))
    
    a$network <- a$parcel %>% gsub("LH_|RH_", "", .) %>% gsub("_.*", "", .)
    a$hemi <- substr(a$parcel, 1, 1)
    
    l[[glm.i]] <- a
    
  }
  
  d[[rsa.i]] <- bind_rows(l, .id = "task")
  
}

d <- as.data.table(bind_rows(d, .id = "similtype"))
d <- d[subj != "448347"]


group.target.trs <- fread(here("out", "stats_univ_hilo_target_schaefer400-07.csv"))
dmcc55b.parcels <- group.target.trs %>% filter(estimate > 0, p.fdr < 0.05) %>% pull(parcel) %>% table
dmcc55b.parcels <- names(dmcc55b.parcels)[dmcc55b.parcels == 4]



```

Transformations:

  * all distance measures are `r similtype`


# cross-parcel correlations

## DMCC55B ROIs (univariate)

```{r crossparcel_dmcc55b, fig.width = 6, fig.height = 6.5, results = "asis"}



for (task.i in tasks) {
  
  cat("\n ")
  cat(sprintf("\n### %s ", task.i))
  cat("\n ")

  
  w.dmcc55b <- d %>% 
    
    .[task.i == task & parcel %in% dmcc55b.parcels, 
      .(b = mean(value)), 
      by = c("task", "parcel", "subj")] %>%
    
    dcast(... ~ parcel, value.var = "b") %>%
    select(where(is.numeric))
  
    
  R.dmcc55b <- cor(w.dmcc55b)
  
  p.R.dmcc55b <- R.dmcc55b %>%
    
    symmat4ggplot %>%
    
    ggplot(aes(v1, v2, fill = value)) +
    geom_raster() +
    
    scale_fill_viridis_c(option = "magma", name = NULL) +
    
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      axis.title = element_blank(), 
      title = element_text(size = rel(1.5)),
      legend.position = "top", panel.border = element_blank(), panel.grid = element_blank()
      )
  
  print(p.R.dmcc55b)
  cat("\n ")
  cat("\n ")
  
  
  
  pca.dmcc55b <- prcomp(w.dmcc55b, scale = TRUE)

  p.eigs <- data.frame(
    eigenvalues = pca.dmcc55b$sdev,
    component = seq_along(pca.dmcc55b$sdev)
    ) %>%
    
    ggplot(aes(component, eigenvalues)) +
    
    geom_line(size = 2) +
    geom_point(size = 4) +
    
    labs(y = expression(sqrt("eigenvalues")))
  
  p.pca.dmcc55b <- pca.dmcc55b$rotation[, 1:2] %>%
    
    as.data.frame %>%
    tibble::rownames_to_column("parcel") %>%
    mutate(network = get.network(parcel)) %>%
    
    ggplot(aes(PC1, PC2, color = network)) +
    
    geom_point(size = 2) +
    geom_text(aes(label = parcel), fontface = "bold", nudge_y = -0.01) +
    scale_color_brewer(type = "qual", palette = 2) +
    
    theme(legend.position = "none")
  
  p.pca <- plot_grid(
    p.eigs,
    p.pca.dmcc55b, ncol = 1, rel_heights = c(1/2, 1)
  )
  
  cat("\n ")
  subchunkify(p.pca, fig_height = 4.5+4.5/2, fig_width = 5)
  cat("\n ")
  
  
}



```






# cross-task correlations


## Per parcel



```{r fig.width = 10, fig.height = 10}

R.task.per.parcel <- enlist(dmcc55b.parcels)
for (parcel.i in dmcc55b.parcels) {
  
  R.task.per.parcel[[parcel.i]] <- 
    
    d[parcel == parcel.i] %>%
    dcast(... ~ task, value.var = "value") %>%
    select(where(is.numeric)) %>%
    cor

}

d.task.per.parcel <- bind_rows(lapply(R.task.per.parcel, symmat4ggplot), .id = "parcel")

d.task.per.parcel %>%
  
  ggplot(aes(v1, v2, fill = value)) +
  geom_raster() +
  geom_text(aes(label = round(value, 1))) +
  
  scale_fill_viridis_c(option = "magma", name = NULL) +
  
  facet_wrap(vars(parcel)) +
  
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    axis.title = element_blank(), 
    title = element_text(size = rel(1.5)),
    legend.position = c(0.92, 0.05), 
    # legend.direction = "horizontal",
    panel.border = element_blank(), panel.grid = element_blank()
    ) +
  
  labs(title = "cross-task correlations in subjects' effect size per DMCC55B ROI")
  
stats.task.per.parcel <- data.frame(
  parcel = names(R.task.per.parcel),
  invdet = 1 / vapply(R.task.per.parcel, det, numeric(1)),
  mean_offdiag = vapply(R.task.per.parcel, function(x) mean(atanh(x[lower.tri(x)])), numeric(1))
)

stats.task.per.parcel <- stats.task.per.parcel %>% reshape2::melt()


```


```{r fig.width = 7, fig.height = 6}

stats.task.per.parcel %>%
  
  ggplot(aes(value, parcel, color = get.network(parcel))) +
  geom_point() +
  geom_segment(aes(x = 0, xend = value, y = parcel, yend = parcel)) +
  
  facet_grid(
    cols = vars(variable), 
    scales = "free_x", 
    labeller =  labeller(variable = c(invdet = "1/det(R)", mean_offdiag = "mean off-diagonal z value")),
    switch = "x"
    ) +

  theme(
    legend.position = "none", 
    axis.title = element_blank(), 
    strip.background = element_blank(), strip.placement = "outside"
    ) +
  
  labs(title = "dependencies in cross-task corrs")


```


