---
title: 'UB55 multivariate analysis: Axcpt all contrasts, group-level'
author: "michael freund"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    highlight: zenburn
    number_sections: true
    theme: spacelab
---


# intro

## Purpose

```{r setup, include = FALSE}

source(here::here("code", "_packages.R"))
source(here("code", "read-behav.R"))
source(here("code", "_vars.R"))
source(here("code", "_atlases.R"))
source(here("code", "_settings.R"))
source(here("code", "_funs.R"))

## data ----

glminfo <- data.frame(
  task = c("Axcpt"),
  name.glm = c(
    "baseline_Cues_EVENTS_censored_shifted"
  )
)
glminfo <- as.data.table(glminfo)

weights1 <- list(
  response01 = c(AX = 1, AY = 1, Ang = 0, BX = 1, BY = 1, Bng = 0) / 4,
  responseLR = c(AX = 1, AY = 0, Ang = 0, BX = 0, BY = 0, Bng = 0),
  ayby       = c(AX = 0, AY = 1, Ang = 0, BX = 0, BY = 0, Bng = 0),
  hilo       = c(AX = 0, AY = 0, Ang = 0, BX = 1, BY = 0, Bng = 0),
  cues       = c(AX = 1, AY = 1, Ang = 1, BX = 0, BY = 0, Bng = 0) / 3
)

weights2 <- list(
  response01 = c(AX = 0, AY = 0, Ang = 1, BX = 0, BY = 0, Bng = 1) / 2,
  responseLR = c(AX = 0, AY = 1, Ang = 0, BX = 1, BY = 1, Bng = 0) / 3,
  ayby       = c(AX = 0, AY = 0, Ang = 0, BX = 0, BY = 1, Bng = 0),
  hilo       = c(AX = 0, AY = 0, Ang = 0, BX = 0, BY = 1, Bng = 0),
  cues       = c(AX = 0, AY = 0, Ang = 0, BX = 1, BY = 1, Bng = 1) / 3
)

contrs <- names(weights1)

similtype <- c(
  "euclidean-cv-unsta-prewh", "euclidean-cv-stand-prewh", "euclidean-cv-unsta-unpre", "euclidean-cv-stand-unpre"
  )


d <- enlist(similtype)
for (rsa.i in similtype) {
  # rsa.i = similtype[1]
  
  a <- readRDS(here("out", "rsa", paste0(rsa.i, "_Axcpt_baseline_Cues_EVENTS_censored_shifted.RDS")))
  sds <- apply(a, c("tr", "parcel", "subj"), function(x) sd(x[lower.tri(x)]))
  a_scale <- sweep(a, MARGIN = 3:5, STATS = sds, FUN = "/")
  
  l <- enlist(names(weights1))
  for (contrast.i in seq_along(weights1)) {
    # contrast.i = 1
    
    dat <- apply(
      a_scale, 
      c("tr", "parcel", "subj"), 
      function(x) weights2[[contrast.i]] %*% x %*% weights1[[contrast.i]]
    )
    dat <- as.data.table(reshape2::melt(dat))
    
    dat$network <- dat$parcel %>% gsub("LH_|RH_", "", .) %>% gsub("_.*", "", .)
    dat$hemi <- substr(dat$parcel, 1, 1)
    
    l[[contrast.i]] <- dat
    
  }
  
  d[[rsa.i]] <- bind_rows(l, .id = "contrast")
  
}

d <- as.data.table(bind_rows(d, .id = "similtype"))
d <- d[subj != "448347"]


facet_labels <- c(
  "euclidean-cv-stand-prewh" = "stand white",
  "euclidean-cv-stand-unpre" = "stand unwhite",
  "euclidean-cv-unsta-prewh" = "unstand white",
  "euclidean-cv-unsta-unpre" = "unstand unwhite" 
)

```



## Notes on analyses.

Contrasts

 * RHS:
```{r}
weights1
```

 * LHS:
```{r}
weights2
```


Cue TRs
```{r}
cue.trs
```



# Network-level

## curves


```{r network_curves_b, fig.height = 7}

d.network.curves <- d[, .(m = mean(value)), by = .(similtype, contrast, network, tr, subj)]

for (contrast.i in contrs) {
  
  p.network.curves  <- d.network.curves %>%
    
    filter(contrast == contrast.i) %>%
    mutate(tr = as.numeric(tr)) %>%
    
    ggplot(aes(tr, m)) +
    geom_hline(yintercept = 0) +
    geom_boxplot(width = 0.5, aes(group = tr)) +
    stat_summary(fun.data = "mean_cl_boot", geom = "ribbon", alpha = 1/2) +
    
    facet_grid(
      vars(similtype), vars(network), 
      scale = "free_y", 
      labeller = labeller(similtype = facet_labels)
      ) +
    scale_x_continuous(breaks = seq(0, 20, 4)) +
    scale_fill_brewer(type = "qual", palette = 2)  +
    
    labs(y = "Mean contrast", x = "TR post stimtime", title = paste0(contrast.i, ", network level"))
  
  print(p.network.curves)
  
}

```




```{r network_curves_t, fig.height = 7}

d.network.curves.group <- d.network.curves %>%

  group_by(contrast, tr, network, similtype) %>%
  summarize(
    p = t.test(m)$p.value,
    t = t.test(m)$statistic,
    b = mean(m)
  ) %>%

  group_by(contrast, tr, similtype) %>%
  mutate(p.fdr = p.adjust(p, "fdr"))


for (contrast.i in contrs) {
  
  p.network.curves.group <- d.network.curves.group %>%
  
    filter(contrast == contrast.i) %>%
  
    mutate(tr = as.numeric(tr)) %>%
  
    ggplot(aes(tr, t, color = similtype, group = similtype)) +
    geom_hline(yintercept = 2, color = "grey50", linetype = "dashed") +
    geom_hline(yintercept = -2, color = "grey50", linetype = "dashed") +
    geom_hline(yintercept = 0) +
  
    geom_line(size = 2) +
  
    facet_wrap(vars(network)) +
    scale_color_brewer(type = "qual", palette = 2, labels = facet_labels) +
    scale_x_continuous(breaks = seq(0, 20, 4)) +
    
    theme(legend.position = c(0.5, 0.15)) +
  
    labs(y = "t statistic", x = "TR post stimtime", title = paste0(contrast.i, ", DMCC34"))
  
  print(p.network.curves.group)
  
}

```


# parcel-level

```{r}

d.parcel.curves.group <- d %>% 
  .[, 
    .(b = mean(value), t = t.test(value)$statistic, p = t.test(value)$p.value), 
    by = .(similtype, contrast, parcel, tr)
    ] %>%
  group_by(contrast, tr, similtype) %>% 
  mutate(p.fdr = p.adjust(p, "fdr"))

```



## curves

```{r fig.height = 7}

counts.parcel.curves.group <- d.parcel.curves.group %>%
  
  group_by(contrast, similtype, tr) %>%
  summarize(
    nparc.activ = sum(b > 0 & p.fdr < 0.05),
    nparc.deactiv = -sum(b < 0 & p.fdr < 0.05)
    ) %>%
  reshape2::melt(id.var = c("contrast", "tr", "similtype"))


```


### counts of significant effects per TR

```{r fig.height = 7}
  
counts.parcel.curves.group %>%
  
  ggplot(aes(as.numeric(tr), value, color = variable)) +
  geom_hline(yintercept = 0) +
  geom_point(size = 2) +
  geom_segment(aes(xend = tr, yend = 0), size = 1) +
  
  facet_grid(vars(similtype), vars(contrast), labeller = labeller(similtype = facet_labels)) +
  scale_color_brewer(type = "qual", palette = 1) +
  scale_x_continuous(breaks = seq(0, 20, 2)) +
  theme(legend.position = "none") +
  
  labs(
    y = "N parc w/ sig. contrast (FDR corrected whole-cortex)", 
    x = "TR post stimtime", title = "timecourse of sig. effects"
    )

```



### runwise univariate ROIs

```{r fig.height = 7}

parcels.univ.conj <- fread(here("out", "conjunction_univ_hilo_target_schaefer400-07.txt"))[[1]]


for (contrast.i in contrs) {
  
  p.parcel.curves  <- d.parcel.curves.group %>%
    
    filter(contrast == contrast.i, parcel %in% parcels.univ.conj) %>%
    mutate(tr = as.numeric(tr)) %>%
    
    ggplot(aes(tr, t, color = similtype, group = similtype)) +
    geom_hline(yintercept = 2, color = "grey50", linetype = "dashed") +
    geom_hline(yintercept = -2, color = "grey50", linetype = "dashed") +
    geom_hline(yintercept = 0) +
  
    geom_line(size = 2) +
  
    facet_wrap(vars(parcel)) +
    scale_color_brewer(type = "qual", palette = 2, labels = facet_labels) +
    scale_x_continuous(breaks = seq(0, 20, 4)) +
    
    theme(legend.position = "top") +
  
    labs(y = "t statistic", x = "TR post stimtime", title = paste0(contrast.i, ", univariate hilo conjunction"))
  
  print(p.parcel.curves)
  
}


```


### largest 20 ROIs


```{r fig.height = 7}


for (contrast.i in contrs) {
  
  parcels.max20 <- d.parcel.curves.group %>% 
          filter(contrast == contrast.i) %>%
          ungroup %>%
          slice_max(order = abs(t), n = 20) %>% pull(parcel) %>% unique
  
  p.parcel.curves  <- d.parcel.curves.group %>% 
    
    filter(contrast %in% contrast.i, parcel %in% parcels.max20) %>%
    
    mutate(tr = as.numeric(tr)) %>%
    
    ggplot(aes(tr, t, color = similtype, group = similtype)) +
    geom_hline(yintercept = 2, color = "grey50", linetype = "dashed") +
    geom_hline(yintercept = -2, color = "grey50", linetype = "dashed") +
    geom_hline(yintercept = 0) +
  
    geom_line(size = 2) +
  
    facet_wrap(vars(parcel)) +
    scale_color_brewer(type = "qual", palette = 2, labels = facet_labels) +
    scale_x_continuous(breaks = seq(0, 20, 4)) +
    
    theme(legend.position = "top") +
  
    labs(y = "t statistic", x = "TR post stimtime", title = paste0(contrast.i, ", 20 parcels with maximum abs(t) stats"))
  
  print(p.parcel.curves)
  
}


```





## maps (cue TRs)



```{r stats}


d.group <- enlist(contrs)
for (contrast.i in contrs) {
  
  
  d.i <- d[contrast %in% contrast.i & tr %in% target.trs$Axcpt]
  
  
  l <- split(d.i, interaction(d.i$parcel, d.i$similtype))
  m <- lapply(l, function(x) lmer(value ~ 1 + (1 | subj), x))
  s <- bind_rows(lapply(m, tidy_lmer), .id = "parcel.similtype")
  s <- cbind(s, reshape2::colsplit(s$parcel.similtype, "\\.", c("parcel", "similtype")))
  s %<>% 
    mutate(
      parcel.similtype = NULL,
      term = NULL,
      p.fdr = p.adjust(p.value, "fdr"), 
      network = get.network(parcel),
      hemi = substr(parcel, 1, 1),
      num.roi = match(parcel, parcellation$key)
      )
  
  
  d.group[[contrast.i]] <- s
  
  
}


lapply(d.group, function(x) filter(x, p.fdr < 0.05 & estimate > 0) %>% nrow)


d.group <- bind_rows(d.group, .id = "contrast")


# fwrite(d.group, here("out", "stats_multiv-euclidean-cv_task_cue_alltasks_schaefer400-07.csv"))


```

Unthresholded and thresholded t-statistics.
Threshold at fdr-corrected p-value (across all parcels) of 0.05.


```{r maps_hilo, fig.height = 7, fig.width = 11, results = "asis"}


for (contrast.i in contrs) {
  for (similtype.i in similtype) {
    
    
    cat(sprintf("\n#### %s %s", contrast.i, similtype.i))
    
    
    d.group %>%
      
      filter(contrast == contrast.i, similtype == similtype.i) %>%
      
      build_overlay("statistic", template = schaefer) %>%
      plot_surface(underlay = hcp, hues = viridis::inferno(500))
    
    
    d.group %>%
      
      filter(contrast == contrast.i, similtype == similtype.i) %>%
      mutate(statistic = ifelse(p.fdr < 0.05, statistic, 0)) %>%
      
      build_overlay("statistic", template = schaefer) %>%
      plot_surface(underlay = hcp, hues = viridis::inferno(500))

    
  }
}


```


