---
title: "Design matrix QC, UB55"
author: "mike freund"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    highlight: zenburn
---


```{r setup, include = FALSE}

## TODO:
## vif as function of dropping terms
##   - cumulative: polort 5, 5+4, 5+4+3, ..., 
##   - each own
## correlation matrices
## problem subjects:
##   - with > 10 vif for regressors of interest: why?
##      - co-linearity with motion, polort, as result of censoring?
##      
##  1. ID 'bad subjects' for each regressor of interest with threshold on VIF
##  2. plot motion R^2, polort R^2, param of interest R^2, by group (bad, good subj)
##  3. 
##    correlation wtih censoring by group
##    # frames censored by group
##    ssq(fd) by group

knitr::opts_chunk$set(echo = FALSE, fig.align = 'center', cache = TRUE)

library(here)
library(dplyr)
library(magrittr)
library(data.table)
library(mikeutils)
library(gifti)
library(cifti)
library(abind)

library(ggplot2)
library(grid)
library(gridExtra)
library(cowplot)

source(here("code", "glms", "write-events_funs.R"))
source(here("code", "read-behav.R"))
source(here("code", "_vars.R"))

## settings

theme_set(theme_bw(base_size = 12))

## xmats
 
xmat_axcpt <- readRDS(here("out", "glms", "xmats_Axcpt_baseline_Cues_EVENTS_censored_shifted.RDS"))[, , !subjs %in% "432332", ]
xmat_cuedts <- readRDS(here("out", "glms", "xmats_Cuedts_baseline_CongruencySwitch_EVENTS_censored_shifted.RDS"))[, , !subjs %in% "432332", ]
xmat_stern <- readRDS(here("out", "glms", "xmats_Stern_baseline_ListLength_EVENTS_censored_shifted.RDS"))[, , !subjs %in% "432332", ]
xmat_stroop <- readRDS(here("out", "glms", "xmats_Stroop_baseline_Congruency_EVENTS_censored_shifted.RDS"))[, , !subjs %in% "432332", ]

```

# About


# VIF



```{r vifs, warning = FALSE}


vifs <- function(X) {
  
  vifs.i <- apply(X, c("subj", "run"), function(.) car::vif(lm(1:nrow(.) ~ . - 1, as.data.frame(.))))
  vifs.i <- reshape2::melt(vifs.i, value.name = "vif", varnames = c("regressor", "subj", "run"))


  vifs.i$regressor.type <- ""
  vifs.i$regressor.type[grep("block", vifs.i$regressor)] <- "block"
  vifs.i$regressor.type[grep("movreg", vifs.i$regressor)] <- "movreg"
  vifs.i$regressor.type[grep("Pol", vifs.i$regressor)] <- "polort"
  vifs.i$regressor.type[-grep("block|movreg|Pol", vifs.i$regressor)] <- "event"

  vifs.i
 
}


s <- setdiff(subjs, c("300618", "432332", "DMCC7297690", "DMCC9850294", "204319", "DMCC9953810"))


vifs_axcpt <- vifs(xmat_axcpt)
vifs_cuedts <- vifs(xmat_cuedts)
vifs_stern <- vifs(xmat_stern[, , s, ])
vifs_stroop <- vifs(xmat_stroop)


X <- xmat_stern[, , c("300618", "DMCC7297690", "DMCC9850294", "204319", "DMCC9953810"), ]
dimnames(X)
duplicated(X, MARGIN = 2:4)


cor(X[, grep("not5RN", dimnames(X)$regressor), "DMCC9953810", 2]) %>% qcor

plot(X[, "not5RN#8", "300618", 1])
plot(X[, "not5RN#7", "300618", 1])


apply(cor(X[, , "300618", 1]), 2, )
View(cor(X[, , "300618", 1]) > 0.99)


# for (subj.i in dimnames(xmat_stern)$subj) {
# for (subj.i in s) {
# 
#   if (subj.i %in% c("300618", "432332", "DMCC7297690", "DMCC9850294", "204319", "DMCC9953810")) next
# 
#   X <- as.data.frame(xmat_stern[, , subj.i, 2])
#   car::vif(lm(1:nrow(X) ~ . - 1, X))
# 
# }

```

# distribution of VIFs for "regressors of interest" across subjects


```{r vifs_plot, fig.width = 10, fig.height = 15}

vifs_axcpt %>%
  
  filter(regressor.type %in% "event") %>%
  
  ggplot(aes(vif, regressor)) +
  geom_boxplot()
  

vifs_cuedts %>%
  
  filter(regressor.type %in% "event") %>%
  
  ggplot(aes(vif, regressor)) +
  geom_boxplot()


vifs_stern %>%
  
  filter(regressor.type %in% "event") %>%
  
  ggplot(aes(vif, regressor)) +
  geom_boxplot()


vifs_stroop %>%
  
  filter(regressor.type %in% "event") %>%
  
  ggplot(aes(vif, regressor)) +
  geom_boxplot()


```

# unique values of regressors

should be 1 or 0 for TENTs ("stick" models)

```{r}

unique_axcpt <- apply(xmat_axcpt, "regressor", function(x) unique(c(x)))
unique_axcpt[-grep("block|Run|movregs", names(unique_axcpt))]



```

